### ISSUE TITLE
installation via pip instructions require auth

### ISSUE THREAD

**Issue by ignacioalvmar** [stefan-urban/opendrive2lanelets-converter#2]
Hi there,

following git clone https://gitlab.lrz.de/koschi/converter.git they ask for credentials.
Can I install via pip? The installation is a unclear to me.

Thanks!

**Comment by stefan-urban** [comment]
Hi!

The current maintained repository can be accessed using this URL:
https://gitlab.com/cps_public/opendrive2lanelet

There you can find instructions to install the converter using pip.

BR Stefan Urban
