### ISSUE TITLE
ZeroDivisionError

### ISSUE THREAD

**Issue by ignacioalvmar** [stefan-urban/opendrive2lanelets-converter#3]
I tried to convert the attached opendrive file but conversion resulted in float division by zero error:
[opendrive.zip](https://github.com/stefan-urban/opendrive2lanelets-converter/files/2798258/opendrive.zip)
```
python3 gui.py 
/home/ignacio/Documents/CAV/opendrive2lanelets-converter/opendriveparser/parser.py:155: FutureWarning: The behavior of this method will change in future versions. Use specific 'len(elem)' or 'elem is not None' test instead.
  if roadType.find("speed"):
Traceback (most recent call last):
  File "gui.py", line 139, in exportAsCommonRoad
    fh.write(self.loadedRoadNetwork.exportCommonRoadScenario().export_to_string())
  File "/home/ignacio/Documents/CAV/opendrive2lanelets-converter/opendrive2lanelet/network.py", line 185, in exportCommonRoadScenario
    filterTypes=filterTypes if isinstance(filterTypes, list) else ['driving', 'onRamp', 'offRamp', 'exit', 'entry']
  File "/home/ignacio/Documents/CAV/opendrive2lanelets-converter/opendrive2lanelet/network.py", line 59, in exportLaneletNetwork
    lanelet = pLane.convertToLanelet()
  File "/home/ignacio/Documents/CAV/opendrive2lanelets-converter/opendrive2lanelet/plane_elements/plane_group.py", line 51, in convertToLanelet
    y2 = (refDistance[1] - refDistance[0]) / self.length * x + refDistance[0]
ZeroDivisionError: float division by zero
```
is it an issue of the opendrive file? i can visualize on the Opendrive viewer tool and it looks good.

**Comment by benjaminor** [comment]
Hi Ignacio,

I'm the current maintainer of this package.
This version on github is actually not the current one, you can download opendrive2lanelet from PyPI: https://pypi.org/project/opendrive2lanelet/

I tested the current code with your xodr file, it converted it w/o problems.
If you have any issues, you can just file one under https://gitlab.com/cps_public/opendrive2lanelet.

Best,
Benjamin

**Comment by stefan-urban** [comment]
Hi,

as Benjamin already stated, he is the current maintainer now. Please use https://gitlab.com/cps_public/opendrive2lanelet in the future. I'm closing this repository now.

BR Stefan Urban
